#define SOCKS5_VERSION 0x05
#define SOCKS5_AUTH_METHOD_NONE 0x01
#define SOCKS5_AUTH_METHOD_USERNAME_PASSWORD 0x02
#define SOCKS5_CMD_TYPE_CONNECT 0x01
#define SOCKS5_CMD_TYPE_BIND 0x01
#define SOCKS5_CMD_TYPE_UDPASSOCIATE 0x03
#define SOCKS5_ADDR_TYPE_IPV4 0x01
#define SOCKS5_ADDR_TYPE_DOMAIN 0x03
#define SOCKS5_ADDR_TYPE_IPV6 0x04

int socks5_client(const char* PROXY_IP, int PROXY_PORT, const char* USERNAME, const char* PASSWORD, const char* TARGET_ADDR, const int TARGET_PORT);
